/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sessions */
        get: operations["get_sessions_api_v1_session_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Session */
        patch: operations["change_session_api_v1_session__session_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get All Sessions */
        get: operations["admin_get_all_sessions_api_v1_admin_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request */
        post: operations["create_request_api_v1_request__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{session_id}/for_query/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request For Query */
        post: operations["create_request_for_query_api_v1_request__session_id__for_query__query_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{session_id}/from_query/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request From Query */
        post: operations["create_request_from_query_api_v1_request__session_id__from_query__query_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{session_id}/from_sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request From Sql */
        post: operations["create_request_from_sql_api_v1_request__session_id__from_sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/{session_id}/linked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Linked Session Request
         * @description Create a request in a new session that is linked to the previous session.
         */
        post: operations["create_linked_session_request_api_v1_session__session_id__linked_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{session_id}/{seq_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Request */
        get: operations["get_single_request_api_v1_request__session_id___seq_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/get_requests/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requests For Session */
        get: operations["get_requests_for_session_api_v1_session_get_requests__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Request
         * @description Delete a request and revert the session to the state
         *     before this request was added.
         */
        delete: operations["delete_request_api_v1_request__request_id__delete"];
        options?: never;
        head?: never;
        /** Update Single Request */
        patch: operations["update_single_request_api_v1_request__request_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get All Requests
         * @description Get all requests for admin with pagination metadata, user info, and search.
         *     Returns total count for proper pagination.
         */
        get: operations["admin_get_all_requests_api_v1_admin_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin Update Request
         * @description Update admin-specific fields on a request (is_test, is_fixed, fix_comment).
         *     When is_fixed is set to True, fixed_by and fixed_ts are automatically populated.
         */
        patch: operations["admin_update_request_api_v1_admin_requests__request_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/data-fetches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get All Data Fetches
         * @description Get all data fetch records for admin with pagination and filtering.
         *     Returns total count for proper pagination.
         */
        get: operations["admin_get_all_data_fetches_api_v1_admin_data_fetches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get All Queries
         * @description Get all queries for admin with pagination, search, and data_fetches.
         *     Returns total count for proper pagination.
         *     Each query includes its associated data_fetches for monitoring.
         */
        get: operations["admin_get_all_queries_api_v1_admin_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/query-explorer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get Query Explorer
         * @description Get query explorer data: queries with their full journey from intent to result.
         *
         *     For each query, returns:
         *     - Query details (SQL, summary, row_count, rating)
         *     - Original intent that started the journey
         *     - All contributing requests with plan info and trace summaries
         *     - Aggregated metrics (plan iterations, SQL attempts, duration, tokens)
         *     - Flags for amendments and replans
         *
         *     Supports expandable rows in the frontend to show request-level details.
         */
        get: operations["admin_get_query_explorer_api_v1_admin_query_explorer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get All Traces
         * @description Get all request traces for admin with pagination.
         *     Returns traces with full step details and summary statistics.
         */
        get: operations["admin_get_all_traces_api_v1_admin_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/traces/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get Request Trace
         * @description Get detailed trace for a specific request.
         *     Returns all trace steps with full metadata and summary.
         */
        get: operations["admin_get_request_trace_api_v1_admin_traces__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/prompt-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get All Prompt Versions
         * @description Get all prompt versions for admin with pagination.
         *     Prompt versions are content-addressable records of prompts used in LLM calls.
         */
        get: operations["admin_get_all_prompt_versions_api_v1_admin_prompt_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/prompt-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get Prompt Version
         * @description Get a specific prompt version by ID.
         *     Returns full prompt content and metadata.
         */
        get: operations["admin_get_prompt_version_api_v1_admin_prompt_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Chart */
        post: operations["generate_chart_api_v1_chart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chart/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart */
        get: operations["get_chart_api_v1_chart__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chart/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Chart Html */
        post: operations["generate_chart_html_api_v1_chart_html_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chart/html/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart Html */
        get: operations["get_chart_html_api_v1_chart_html__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Queries */
        get: operations["get_all_queries_api_v1_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query Data */
        get: operations["get_query_data_api_v1_data__query_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Data Fetch
         * @description Cancel or unsubscribe from a running data fetch.
         *
         *     Behavior:
         *     - If user is the only subscriber → cancel the Celery task entirely
         *     - If other users are subscribed → just unsubscribe this user (task continues)
         *
         *     Returns:
         *         - status: "cancelled" if task was terminated
         *         - status: "unsubscribed" if user was removed but task continues
         *         - status: "not_found" if no running task exists
         */
        delete: operations["cancel_data_fetch_api_v1_data__query_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Data Fetch Notification
         * @description Update notification settings for a running data fetch.
         *
         *     Allows users to add or remove email notification for when the fetch completes.
         *
         *     Request body:
         *         - notify: bool - Whether to send notification on complete
         *         - user_email: str (optional) - Email for notification
         *           (uses auth email if not provided)
         *
         *     Returns:
         *         - status: "updated" if notification setting was updated
         *         - status: "not_found" if no running task exists
         */
        patch: operations["update_data_fetch_notification_api_v1_data__query_id__patch"];
        trace?: never;
    };
    "/api/v1/data/sse/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Data Fetch
         * @description SSE endpoint for async data fetching.
         *
         *     Flow:
         *     1. Validates query and auth
         *     2. Launches Celery task for data fetching
         *     3. Streams progress events to client
         *     4. Returns final data when ready
         *
         *     Args:
         *         request_id: Optional request ID for linking data_fetch to a request.
         *                    Only pass this when fetching from a grid session context.
         *                    Dashboard items and detached /q/:id views should not pass this.
         */
        get: operations["stream_data_fetch_api_v1_data_sse__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Telemetry Sse
         * @description SSE endpoint for system telemetry (worker stats, DB pool stats).
         *     Sends updates every 5 seconds.
         */
        get: operations["telemetry_sse_api_v1_telemetry_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query Metadata */
        get: operations["get_query_metadata_api_v1_query__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sse/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Request Updates
         * @description Server-Sent Events endpoint for real-time request status updates.
         *
         *     Listens to PostgreSQL NOTIFY events on the 'request_update' channel
         *     and streams updates for the specified session to connected clients.
         *
         *     The trigger sends notifications with this payload:
         *     {
         *         "request_id": "uuid",
         *         "session_id": "uuid",
         *         "status": "status_enum",
         *         "updated_at": timestamp,
         *         "has_response": bool,
         *         "has_error": bool,
         *         "sequence_number": int
         *     }
         */
        get: operations["stream_request_updates_api_v1_sse__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddLinkedRequestModel */
        AddLinkedRequestModel: {
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string | null;
            /** @default 2 */
            version: components["schemas"]["Version"];
            /** Request */
            request: string;
            /** @default Multistep */
            flow: components["schemas"]["FlowType"] | null;
            /** @default OpenAI */
            model: components["schemas"]["ModelType"] | null;
            /** @default  */
            db: components["schemas"]["DBType"] | null;
            refs?: components["schemas"]["Refs"] | null;
        };
        /** AddRequestModel */
        AddRequestModel: {
            /** @default 1 */
            version: components["schemas"]["Version"];
            /** Request */
            request: string;
            /** @default tbd */
            request_type: components["schemas"]["InteractiveRequestType"] | null;
            /** @default Multistep */
            flow: components["schemas"]["FlowType"] | null;
            /** @default OpenAI */
            model: components["schemas"]["ModelType"] | null;
            /** @default  */
            db: components["schemas"]["DBType"] | null;
            refs?: components["schemas"]["Refs"] | null;
            /** Query Id */
            query_id?: string | null;
        };
        /**
         * AdminDataFetchesResponse
         * @description Paginated response for admin data fetches endpoint.
         */
        AdminDataFetchesResponse: {
            /** Data Fetches */
            data_fetches: components["schemas"]["GetDataFetchModel"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminPromptVersionsResponse
         * @description Paginated response for admin prompt versions endpoint.
         */
        AdminPromptVersionsResponse: {
            /** Prompt Versions */
            prompt_versions: components["schemas"]["GetPromptVersionModel"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminQueriesResponse
         * @description Paginated response for admin queries endpoint.
         */
        AdminQueriesResponse: {
            /** Queries */
            queries: components["schemas"]["GetQueryModel"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminRequestsResponse
         * @description Paginated response for admin requests endpoint.
         */
        AdminRequestsResponse: {
            /** Requests */
            requests: components["schemas"]["GetRequestModel"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AdminTracesResponse
         * @description Paginated response for admin traces endpoint.
         */
        AdminTracesResponse: {
            /** Traces */
            traces: components["schemas"]["GetRequestTraceModel"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ChartMetadata
         * @description Chart visualization metadata for query results.
         *
         *     - suggested_chart: LLM's suggested chart type based on query intent
         *     - available_charts: Empirically validated chart types based on result structure
         *     - chart_config: Optional hints for chart rendering (axis labels, title, etc.)
         */
        ChartMetadata: {
            /** Suggested Chart */
            suggested_chart?: string | null;
            /** Available Charts */
            available_charts?: string[] | null;
            /** Chart Config */
            chart_config?: {
                [key: string]: unknown;
            } | null;
        };
        /** ChartRequest */
        ChartRequest: {
            /** Code */
            code: string;
        };
        /** ChartStructuredRequest */
        ChartStructuredRequest: {
            chart_type: components["schemas"]["ChartType"];
            /** Labels */
            labels: string[];
            /** Rows */
            rows: unknown[][];
        };
        /**
         * ChartType
         * @enum {string}
         */
        ChartType: "Pie" | "Bar";
        /** Column */
        Column: {
            /** Id */
            id?: string;
            /** Summary */
            summary?: string | null;
            /** Column Name */
            column_name?: string | null;
            /** Column Alias */
            column_alias?: string | null;
            /** Column Type */
            column_type?: string | null;
            /** Column Description */
            column_description?: string | null;
        };
        /** CreateQueryFromSqlModel */
        CreateQueryFromSqlModel: {
            /** Request */
            request: string;
            /** Sql */
            sql?: string;
            /**
             * Ai Generated
             * @default false
             */
            ai_generated: boolean;
            /** Ai Context */
            ai_context?: {
                [key: string]: unknown;
            } | null;
            /** Data Source */
            data_source?: string | null;
            /** Db Dialect */
            db_dialect?: string | null;
        };
        /** CreateSessionModel */
        CreateSessionModel: {
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string | null;
            /** Parent */
            parent?: string | null;
            refs?: components["schemas"]["Refs"] | null;
        };
        /**
         * DBType
         * @enum {string}
         */
        DBType: "" | "NWH" | "V2";
        /**
         * DataFetchStatus
         * @enum {string}
         */
        DataFetchStatus: "pending" | "running" | "success" | "error" | "cancelled" | "timed_out";
        /**
         * FlowType
         * @enum {string}
         */
        FlowType: "OpenAISimple" | "OpenAISimpleNWH" | "OpenAISimpleV2" | "GeminiSimple" | "GeminiSimpleNWH" | "GeminiSimpleV2" | "DeepseekSimple" | "DeepseekSimpleNWH" | "DeepseekSimpleV2" | "AnthropicSimple" | "AnthropicSimpleNWH" | "AnthropicSimpleV2" | "OpenAIMultisteps" | "OpenAIMultistep" | "GeminiMultistep" | "DeepseekMultistep" | "AnthropicMultistep" | "Simple" | "Multistep" | "DataOnly" | "MCP" | "Flex" | "LangGraph" | "Interactive";
        /**
         * GetDataFetchModel
         * @description Model for reading a data fetch record.
         */
        GetDataFetchModel: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Request Id */
            request_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Requestor */
            requestor: string;
            status: components["schemas"]["DataFetchStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Query Params */
            query_params?: {
                [key: string]: unknown;
            } | null;
            /** Row Count */
            row_count?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /**
         * GetPromptVersionModel
         * @description Model for reading a prompt version record.
         */
        GetPromptVersionModel: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Content Hash */
            content_hash: string;
            /** Source */
            source: string;
            /** Source Version */
            source_version?: string | null;
            prompt_item_type: components["schemas"]["PromptItemType"];
            /** Content */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GetQueryModel */
        GetQueryModel: {
            /** Request */
            request: string;
            /** Intent */
            intent?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Sql */
            sql?: string | null;
            /** Row Count */
            row_count?: number | null;
            /** Columns */
            columns?: components["schemas"]["Column"][] | null;
            chart?: components["schemas"]["ChartMetadata"] | null;
            /**
             * Ai Generated
             * @default true
             */
            ai_generated: boolean;
            /** Ai Context */
            ai_context?: {
                [key: string]: unknown;
            } | null;
            /** Data Source */
            data_source?: string | null;
            /** Db Dialect */
            db_dialect?: string | null;
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            } | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Err */
            err?: string | null;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Request Id */
            request_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Data Fetches */
            data_fetches?: components["schemas"]["GetDataFetchModel"][] | null;
        };
        /** GetRequestModel */
        GetRequestModel: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Sequence Number */
            sequence_number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Request */
            request: string;
            /** Response */
            response?: string | null;
            /** Sql */
            sql?: string | null;
            /** Rating */
            rating?: number | null;
            /** Review */
            review?: string | null;
            status: components["schemas"]["RequestStatus"];
            /** Intent */
            intent?: string | null;
            /** Assumptions */
            assumptions?: string | null;
            /** Intro */
            intro?: string | null;
            /** Outro */
            outro?: string | null;
            /** Raw Data Labels */
            raw_data_labels?: string[] | null;
            /** Raw Data Rows */
            raw_data_rows?: (string | number)[][] | null;
            /** Csv */
            csv?: string | null;
            /** Chart */
            chart?: string | null;
            /** Chart Url */
            chart_url?: string | null;
            /** Err */
            err?: string | null;
            /** Preset */
            preset?: string | null;
            session?: components["schemas"]["GetSessionModel"] | null;
            refs?: components["schemas"]["Refs"] | null;
            /** Linked Session Id */
            linked_session_id?: string | null;
            query?: components["schemas"]["GetQueryModel"] | null;
            view?: components["schemas"]["View"] | null;
            /** Data Fetches */
            data_fetches?: components["schemas"]["GetDataFetchModel"][] | null;
            query_plan?: components["schemas"]["QueryPlan"] | null;
            /** Response Type */
            response_type?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Is Test */
            is_test?: boolean | null;
            /** Is Fixed */
            is_fixed?: boolean | null;
            /** Fixed By */
            fixed_by?: string | null;
            /** Fixed Ts */
            fixed_ts?: string | null;
            /** Fix Comment */
            fix_comment?: string | null;
        };
        /**
         * GetRequestTraceModel
         * @description Full trace for a request including all steps.
         */
        GetRequestTraceModel: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Steps */
            steps: components["schemas"]["GetTraceStepModel"][];
            summary: components["schemas"]["TraceSummary"];
        };
        /** GetSessionModel */
        GetSessionModel: {
            /** User */
            user: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Parent */
            parent?: string | null;
            refs?: components["schemas"]["Refs"] | null;
            /** Message Count */
            message_count?: number | null;
        };
        /**
         * GetTraceStepModel
         * @description Model for reading a trace step record.
         */
        GetTraceStepModel: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Step Number */
            step_number: number;
            step_type: components["schemas"]["TraceStepType"];
            /** Model */
            model?: string | null;
            /** Tokens In */
            tokens_in?: number | null;
            /** Tokens Out */
            tokens_out?: number | null;
            /** Input Hash */
            input_hash?: string | null;
            /** Output Raw */
            output_raw?: string | null;
            /** Output Parsed */
            output_parsed?: {
                [key: string]: unknown;
            } | null;
            /** Tool Name */
            tool_name?: string | null;
            /** Tool Input */
            tool_input?: {
                [key: string]: unknown;
            } | null;
            /** Prompt Version Ids */
            prompt_version_ids?: string[] | null;
            /** Validation Type */
            validation_type?: string | null;
            /** Validation Success */
            validation_success?: boolean | null;
            /** Validation Errors */
            validation_errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InteractiveRequestType
         * @enum {string}
         */
        InteractiveRequestType: "tbd" | "interactive_query" | "data_analysis" | "general_chat" | "disambiguation" | "linked_session" | "linked_query" | "manual_query" | "discovery" | "plan_approval" | "plan_amendment" | "clarification" | "clarification_response";
        /**
         * ModelType
         * @enum {string}
         */
        ModelType: "OpenAI" | "Gemini" | "Deepseek" | "Anthropic";
        /**
         * PatchAdminRequestModel
         * @description Model for updating admin-specific fields on a request.
         */
        PatchAdminRequestModel: {
            /** Is Test */
            is_test?: boolean | null;
            /** Is Fixed */
            is_fixed?: boolean | null;
            /** Fix Comment */
            fix_comment?: string | null;
        };
        /** PatchSessionModel */
        PatchSessionModel: {
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /**
         * PromptItemType
         * @enum {string}
         */
        PromptItemType: "DBStruct" | "QueryExample" | "DataDescription" | "RefSources" | "Instruction" | "DataSample" | "SlotSchema" | "SQLDialect" | "DomainModel" | "AssembledPrompt";
        /**
         * QueryExplorerItem
         * @description A query with its full journey from intent to result.
         */
        QueryExplorerItem: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Summary */
            summary?: string | null;
            /** Sql */
            sql?: string | null;
            /** Row Count */
            row_count?: number | null;
            /** Rating */
            rating?: number | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** User */
            user?: string | null;
            /** Original Intent */
            original_intent?: string | null;
            /**
             * Plan Iterations
             * @default 0
             */
            plan_iterations: number;
            /**
             * Sql Attempts
             * @default 0
             */
            sql_attempts: number;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /**
             * Total Tokens In
             * @default 0
             */
            total_tokens_in: number;
            /**
             * Total Tokens Out
             * @default 0
             */
            total_tokens_out: number;
            /**
             * Requests
             * @default []
             */
            requests: components["schemas"]["QueryExplorerRequestSummary"][];
            /**
             * Had Replan
             * @default false
             */
            had_replan: boolean;
            /**
             * Had Amendments
             * @default false
             */
            had_amendments: boolean;
            /**
             * Data Fetches
             * @default []
             */
            data_fetches: components["schemas"]["GetDataFetchModel"][];
        };
        /**
         * QueryExplorerRequestSummary
         * @description Summary of a request that contributed to a query.
         */
        QueryExplorerRequestSummary: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Request Type */
            request_type?: string | null;
            /** Request Text */
            request_text: string;
            status: components["schemas"]["RequestStatus"];
            /**
             * Has Plan
             * @default false
             */
            has_plan: boolean;
            /** Plan Summary */
            plan_summary?: string | null;
            /** Plan Tables */
            plan_tables?: string[] | null;
            /**
             * Sql Attempts
             * @default 0
             */
            sql_attempts: number;
            /**
             * Sql Success
             * @default false
             */
            sql_success: boolean;
            /** Outcome */
            outcome?: string | null;
            /**
             * Has Trace
             * @default false
             */
            has_trace: boolean;
            /**
             * Trace Llm Calls
             * @default 0
             */
            trace_llm_calls: number;
            /**
             * Trace Repairs
             * @default 0
             */
            trace_repairs: number;
            /**
             * Trace Errors
             * @default 0
             */
            trace_errors: number;
            /**
             * Trace Duration Ms
             * @default 0
             */
            trace_duration_ms: number;
        };
        /**
         * QueryExplorerResponse
         * @description Paginated response for query explorer endpoint.
         */
        QueryExplorerResponse: {
            /** Queries */
            queries: components["schemas"]["QueryExplorerItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * QueryPlan
         * @description Human-readable query plan for user approval before SQL generation.
         *
         *     This captures the LLM's understanding of what the query will do,
         *     allowing users to verify intent before SQL is generated.
         */
        QueryPlan: {
            /**
             * Tables
             * @default []
             */
            Tables: string[];
            /**
             * Primarytable
             * @default
             */
            PrimaryTable: string;
            /**
             * Joins
             * @default []
             */
            Joins: (components["schemas"]["QueryPlanJoin"] | string)[];
            /**
             * Columnsselected
             * @default []
             */
            ColumnsSelected: string[];
            /**
             * Filters
             * @default []
             */
            Filters: (components["schemas"]["QueryPlanFilter"] | string)[];
            /**
             * Aggregations
             * @default []
             */
            Aggregations: (components["schemas"]["QueryPlanAggregation"] | string)[];
            /**
             * Grouping
             * @default []
             */
            Grouping: string[];
            /**
             * Ordering
             * @default []
             */
            Ordering: string[];
            /** Limit */
            Limit?: number | string | null;
            /**
             * Assumptions
             * @default []
             */
            Assumptions: string[];
            /**
             * Defaultparameters
             * @default []
             */
            DefaultParameters: string[];
            /**
             * Plansummary
             * @default
             */
            PlanSummary: string;
            /**
             * Estimated Complexity
             * @default moderate
             */
            estimated_complexity: string;
            /** Reason For Approval */
            reason_for_approval?: string | null;
            /** Relevant Schema */
            relevant_schema?: string | null;
            /**
             * Columns Referenced
             * @default []
             */
            columns_referenced: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * QueryPlanAggregation
         * @description Describes an aggregation in the query plan.
         */
        QueryPlanAggregation: {
            /** Function */
            function?: string | null;
            /** Column */
            column?: string | null;
            /** Alias */
            alias?: string | null;
            /** Description */
            description?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * QueryPlanFilter
         * @description Describes a filter/WHERE condition in the query plan.
         */
        QueryPlanFilter: {
            /** Column */
            column?: string | null;
            /** Operator */
            operator?: string | null;
            /** Value */
            value?: string | null;
            /**
             * Source
             * @default inferred
             */
            source: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * QueryPlanJoin
         * @description Describes a join between two tables in the query plan.
         */
        QueryPlanJoin: {
            /** Left Table */
            left_table?: string | null;
            /** Right Table */
            right_table?: string | null;
            /** Type */
            type?: string | null;
            /** Condition */
            condition?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Refs */
        Refs: {
            /** Parent */
            parent?: string | null;
            /** Steps */
            steps?: string[] | null;
            /** Cols */
            cols?: string[] | null;
            /** Rows */
            rows?: (string | number)[][] | null;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "New" | "Intent" | "Planning" | "FeedbackRequested" | "SQL" | "DataFetch" | "Retry" | "Finalizing" | "InProgress" | "Scheduled" | "Error" | "Done" | "Cancelled";
        /**
         * TraceStepType
         * @enum {string}
         */
        TraceStepType: "request_context" | "prompt_assembly" | "mcp_call" | "llm_call" | "validation" | "repair" | "sql_execution" | "error";
        /**
         * TraceSummary
         * @description Summary of trace execution for quick stats on request table.
         */
        TraceSummary: {
            /** Total Steps */
            total_steps: number;
            /** Llm Calls */
            llm_calls: number;
            /** Mcp Calls */
            mcp_calls: number;
            /** Validations */
            validations: number;
            /** Repairs */
            repairs: number;
            /** Total Tokens In */
            total_tokens_in: number;
            /** Total Tokens Out */
            total_tokens_out: number;
            /** Total Duration Ms */
            total_duration_ms: number;
            /** Has Errors */
            has_errors: boolean;
        };
        /**
         * UpdateNotificationRequest
         * @description Request body for updating notification settings.
         */
        UpdateNotificationRequest: {
            /** Notify */
            notify: boolean;
            /** User Email */
            user_email?: string | null;
        };
        /** UpdateRequestStatusModel */
        UpdateRequestStatusModel: {
            /** Review */
            review?: string | null;
            /** Rating */
            rating?: number | null;
            status?: components["schemas"]["RequestStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Version
         * @enum {integer}
         */
        Version: 1 | 2;
        /** View */
        View: {
            /** Sort By */
            sort_by?: string | null;
            /** Sort Order */
            sort_order?: string | null;
            /** Limit */
            limit?: number | null;
            /** Offset */
            offset?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_sessions_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionModel"][];
                };
            };
        };
    };
    create_session_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_session_api_v1_session__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSessionModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_sessions_api_v1_admin_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_v1_request__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_for_query_api_v1_request__session_id__for_query__query_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                query_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_from_query_api_v1_request__session_id__from_query__query_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_from_sql_api_v1_request__session_id__from_sql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQueryFromSqlModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_linked_session_request_api_v1_session__session_id__linked_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLinkedRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_request_api_v1_request__session_id___seq_num__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                seq_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requests_for_session_api_v1_session_get_requests__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_request_api_v1_request__request_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_single_request_api_v1_request__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestStatusModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_requests_api_v1_admin_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["RequestStatus"] | null;
                /** @description Search in request, SQL, or user */
                search?: string | null;
                /** @description Filter to requests with rating or review */
                has_feedback?: boolean | null;
                /** @description Filter by is_test flag */
                is_test?: boolean | null;
                /** @description Filter by is_fixed flag */
                is_fixed?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRequestsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_request_api_v1_admin_requests__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAdminRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_data_fetches_api_v1_admin_data_fetches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["DataFetchStatus"] | null;
                /** @description Filter by query ID */
                query_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDataFetchesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_queries_api_v1_admin_queries_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Search in request, SQL, or summary */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQueriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_query_explorer_api_v1_admin_query_explorer_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Search in request, SQL, or summary */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryExplorerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_traces_api_v1_admin_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTracesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_request_trace_api_v1_admin_traces__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequestTraceModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_all_prompt_versions_api_v1_admin_prompt_versions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by prompt item type */
                prompt_type?: components["schemas"]["PromptItemType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPromptVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_prompt_version_api_v1_admin_prompt_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPromptVersionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_chart_api_v1_chart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_api_v1_chart__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a PNG image file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Chart not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_chart_html_api_v1_chart_html_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartStructuredRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_html_api_v1_chart_html__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a HTML file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Chart not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_queries_api_v1_query_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetQueryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_data_api_v1_data__query_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort_by?: string | null;
                sort_order?: string;
            };
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_data_fetch_api_v1_data__query_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_data_fetch_notification_api_v1_data__query_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_data_fetch_api_v1_data_sse__query_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort_by?: string | null;
                sort_order?: string;
                notify_on_complete?: boolean;
                user_email?: string | null;
                force?: boolean;
                /** @description Request ID for tracking (grid session context only) */
                request_id?: string | null;
            };
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetry_sse_api_v1_telemetry_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_query_metadata_api_v1_query__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetQueryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_request_updates_api_v1_sse__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
