apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-meta-v2-providers
  labels:
    app.kubernetes.io/name: db-meta-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
